name: Janpara Auto Research
on:
  schedule:
    - cron: '0 * * * *' # 毎時0分に自動実行
  workflow_dispatch: # 手動で動かすボタンを作る
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install libraries
        run: pip install -r requirements.txt
      - name: Execute script
        env:
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python main.py
